### ISSUE TITLE
More Discovery about Travel Scroll transformation bug

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#52] opened 2015-05-22 19:27 UTC
I was transformed in (form of the cougar) mode when I entered Underhenge today,  While within the henge the ability ran out but I remained within the (form of a cougar) 'Antlion' shape.  Since my shape was wrong and feeling exiting into the world would crash the server I decided to do the (form of a cougar) spell while within the henge hoping to have the buff button rematerialize and then have the ability to hit it to change back into normal shape before exiting the blue portal.   Well that isn't what happened, what happened was the game crashed... so it seems that being inside a dungeon at all while in a feral form is a bad idea.

**Comment by Heathendel** [comment] 2015-05-22 20:10
Okay I know Em noticed a bug yesterday involving entering and exiting
dungeons he's planning to fix it today most of the problems your talking
Bout are from that bug

**Comment by rockfireredmoon** [comment] 2015-05-25 21:45
Seems like there is still a problem and MAY be the cause of crashes too. Heiffer got this issue causing sunday nights crah.

**Comment by rockfireredmoon** [comment] 2015-05-26 21:17
Ok false alarm, I think this was more instance scripts, same as billy had. This is now fixed.

**Closed by rockfireredmoon** 2015-05-26 21:17 UTC
