### ISSUE TITLE
Bounders Day Books 

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#831] opened 2019-03-31 18:43 UTC
A ticket to track Bounders Day Books. 

Done so far

- Book pages created
- 4 Book Creatures Created
- 4 Book Items Created
- 2 Spawns placed (@LiskaQuicksilver  I could only find 2, im guessing because you got stopped by the cogs!)
- Book crafting for these books (effectively the reward for the quest)

To do

- Exchange book for another reward?
- Add a quest

**Comment by LiskaQuicksilver** [comment] 2019-03-31 20:15
After some further investigating last night I discovered the cause of the problem. Only one of the four book 'creatures' is working...the first one. The other three have spawn issues and spawn as a cog. Because I had tried to spawn the second one in location 2, it was what started causing the issues. Please look into it.

**Comment by LiskaQuicksilver** [comment] 2019-04-01 00:01
These are ready. Closing.

**Closed by LiskaQuicksilver** 2019-04-01 00:01 UTC
